Repository DdangDdang5/Frontend, pull requests merged in 2022-09, with the labels that each got.

#12 [Feat] 마이프로필 페이지 구현중!
  src/App.js
  src/components/auction/Auction.jsx
  src/components/footer/Footer.styled.js
  src/components/modal/Modal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/mypage/Mypage.jsx
Labels: MVP P0

#13 [bug] 서버 배포시 파일명 오류로 인해 파일명 수정
  src/components/auction/Auction.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/mypage/Mypage.jsx
Labels: bug

#14 [Feat]auctionList css 레이아웃 변경
  src/components/auction/Auction.jsx
  src/components/footer/Footer.styled.js
  src/pages/auctionList/AuctionList.jsx
  src/redux/modules/AuctionListSlice.js
  src/shared/Api.jsx
Labels: MVP P1

#20 [Feat] 옥션 리스트 페이지 뷰, 리스트 디테일 페이지 뷰, 프로필 수정 페이지 뷰 완성
  src/components/auction/Auction.jsx
  src/components/header/Header.styled.js
  src/index.css
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/profileEdit/ProfileEdit.jsx
Labels: MVP P0, MVP P1

#21 [Feat] 로그인, 회원가입 화면 및 기능 수정
  package.json
  src/components/footer/Footer.styled.js
  src/elements/button/Button.jsx
  src/index.js
  src/pages/auctionList/AuctionList.jsx
  src/pages/login/Login.jsx
  src/pages/signUp/SignUp.jsx
  src/redux/modules/MemberSlice.js
  src/shared/Api.jsx
  src/shared/Cookie.jsx
  src/shared/Kakao.jsx
  src/shared/KakaoApi.jsx
  src/shared/Theme.jsx
  yarn.lock
Labels: enhancement

#24 [Feat] 서버 연결 뿌려주기 진행중
  src/App.js
  src/components/auction/Auction.jsx
  src/components/footer/Footer.styled.js
  src/components/modal/Modal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/AuctionSlice.js
  src/shared/Api.jsx
Labels: MVP P1

#27 [modify] auctionDetail 서버 데이터 get 오류 수정중
  src/components/auction/Auction.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/AuctionSlice.js
Labels: MVP P1

#28 [feat] auctionList 지역 modal view 구현 완료
  src/App.js
  src/components/modal/Modal.jsx
  src/index.js
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/AuctionSlice.js
  src/redux/modules/ModalSlice.js
  src/redux/modules/MypageSlice.js
Labels: MVP P1

#29 [feat] auctionList modal 웹페이지 모바일 페이지 완벽 뷰 구현
  src/components/auction/Auction.jsx
  src/components/modal/Modal.jsx
  src/pages/auctionList/AuctionList.jsx
Labels: MVP P1

#30 [feat] 옥션리스트 모달 에니메이션 구현중
  src/components/modal/Modal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
Labels: MVP P1

#32 [Feat] 소셜 로그인 수정
  src/App.js
  src/pages/login/Login.jsx
  src/pages/login/Login.styled.jsx
  src/pages/signUp/SignUp.jsx
  src/redux/modules/MemberSlice.js
  src/shared/Cookie.jsx
  src/shared/Kakao.jsx
Labels: MVP P0

#33 [Feat] 옥션 상세 페이지 하단부 구현중, 플러스 버튼 컴포넌트 생성
  src/App.js
  src/components/button/PlusButton.jsx
  src/components/footer/Footer.jsx
  src/components/modal/Modal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/redux/modules/ModalSlice.js
Labels: MVP P1

#34 [Feat] 검색 화면 View 구현
  src/App.js
  src/components/search/TitleSearch.jsx
  src/pages/login/Login.jsx
  src/pages/login/Login.styled.jsx
  src/pages/search/Search.jsx
  src/pages/search/SearchTitle.jsx
  src/pages/signUp/SignUp.jsx
  src/pages/signUp/SignUp.styled.jsx
  src/redux/modules/MemberSlice.js
  src/shared/Theme.jsx
Labels: enhancement

#36 [Feat] 포스팅 이중모달 만드는중
  src/App.js
  src/components/button/PlusButton.jsx
  src/components/modal/CategoryModal.jsx
  src/components/modal/PlusBtnBoxModal.jsx
Labels: MVP P1

#37 [Feat] 옥션 추가 페이지 뷰, 마이페이지 뷰, 관심, 참여, 경매 뷰 완료
  src/App.js
  src/components/auction2/Auction2.jsx
  src/components/auctionStateNav/AuctionStateNav.jsx
  src/components/button/PlusButton.jsx
  src/components/modal/PlusBtnBoxModal.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
Labels: MVP P0, MVP P1

#39 [Feat] 검색화면 기능 수정
  package.json
  src/App.js
  src/components/search/TitleSearch.jsx
  src/pages/login/Login.jsx
  src/pages/login/Login.styled.jsx
  src/pages/search/Search.jsx
  src/pages/search/SearchCard.jsx
  src/pages/search/SearchTitle.jsx
  src/pages/signUp/SignUp.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/MemberSlice.js
  src/redux/modules/SearchSlice.js
  src/shared/Api.jsx
  src/shared/Cookie.jsx
  src/shared/Kakao.jsx
  yarn.lock
Labels: enhancement

#41 [Feat] 옥션 포스팅 기능 서버 통신완료
  src/App.js
  src/components/button/PlusButton.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/AuctionSlice.js
  src/redux/modules/MemberSlice.js
  src/shared/Api.jsx
Labels: MVP P1

#51 [feat] 마이페이지 프로필 메인 수정중
  src/App.js
  src/components/auction/AuctionColumn.jsx
  src/components/auction/AuctionRow.jsx
  src/components/auction2/Auction2.jsx
  src/components/auctionStateNav/AuctionStateNav.jsx
  src/components/header/Header.jsx
  src/components/modal/CategoryModal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/main/Main.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/pages/search/Search.jsx
  src/pages/signUp/SignUp.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/ModalSlice.js
  src/redux/modules/MypageSlice.js
  src/shared/Kakao.jsx
Labels: MVP P0, MVP P1

#54 [Feat] 옥션리스트 페이지네이션 기능, 마이페이지 페이지 구분 완료, 마이페이지 페이지네이션 기능 추가중
  src/components/auction/AuctionRow.jsx
  src/components/auctionCategoryList/AuctionCategoryList.jsx
  src/components/auctionStateNav/AuctionStateNav.jsx
  src/components/header/Header.jsx
  src/components/modal/CategoryModal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/chat/Chat.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/ModalSlice.js
  src/redux/modules/MypageSlice.js
  src/shared/Kakao.jsx
Labels: MVP P2

#58 [Feat] 옥션 상세 페이지 안정화 작업, 옥션 프로필 페이지 상세 작업
  src/components/button/PlusButton.jsx
  src/components/modal/CategoryModal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/ModalSlice.js
  src/redux/modules/MypageSlice.js
Labels: MVP P0, MVP P1

#62 [feat] 옥션리스트 삭제후 새로고침 안하면 랜더링 안되던것 해결
  src/components/header/Header.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/redux/modules/AuctionListSlice.js
Labels: MVP P1

#66 [Feat] 로그인 기능 추가, 이미지 슬라이더 만드는중
  src/components/auction/Slider.jsx
  src/components/modal/menuModal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/login/Login.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/modules/MypageSlice.js
  src/shared/Api.jsx
Labels: MVP P1

#79 [Feat] 옥션 디테일 페이지 타이머 기능 추가 완료
  src/components/auction/Slider.jsx
  src/components/countDownTimer/CountDownTimer.jsx
  src/components/countDownTimer/DateTimeDisplay.jsx
  src/components/hooks/UseCountDown.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionEdit/AuctionEdit.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/chat/Chat.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/redux/modules/ModalSlice.js
  src/redux/modules/MyPageSlice.js
Labels: MVP P2

#85 [Feat] 옥션 수정 기능 하는중
  package.json
  public/index.html
  src/App.js
  src/components/header/Header.jsx
  src/components/modal/MenuModal.jsx
  src/elements/button/PlusButton.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionEdit/AuctionEdit.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/chatList/ChatList.jsx
  src/pages/main/Main.jsx
  src/pages/myPage/MyPage.jsx
  src/redux/modules/AuctionListSlice.js
  yarn.lock
Labels: MVP P2

#89 [Feat] Feature/css fix
  src/components/auction/AuctionColumn.jsx
  src/components/auction/AuctionRow.jsx
  src/components/header/Header.styled.js
  src/components/modal/MenuModal.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/main/Main.styled.js
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/modules/AuctionSlice.js
  src/redux/modules/MyPageSlice.js
  src/shared/images/icon/Camera.svg
  src/shared/images/icon/Event.svg
  src/shared/images/icon/Login.svg
  src/shared/images/icon/Logout.svg
  src/shared/images/icon/Notice.svg
  src/shared/images/icon/ProfileEdit.svg
  src/shared/images/icon/Questions.svg
  src/shared/images/index.js
Labels: MVP P2

#91 [feat] 마이페이지 괸심 수정
  src/components/auction/AuctionRow.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/modules/MyPageSlice.js
Labels: MVP P2

#92 [Feat] 옥션 공지사항 페이지 만드는중
  src/App.js
  src/components/auction/AuctionBox.jsx
  src/components/auction/AuctionColumn.jsx
  src/components/auction/AuctionRow.jsx
  src/components/auction/Slider.jsx
  src/components/auctionStateNav/AuctionStateNav.jsx
  src/components/countDownTimer/CountDownTimer.jsx
  src/components/countDownTimer/DateTimeDisplay.jsx
  src/components/header/Header.jsx
  src/components/hooks/UseCountDown.jsx
  src/components/modal/CategoryModal.jsx
  src/components/modal/MenuModal.jsx
  src/components/modal/PlusBtnBoxModal.jsx
  src/components/notice/NoticeContent.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionDone/AuctionDone.jsx
  src/pages/auctionEdit/AuctionEdit.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/pages/notice/Notice.jsx
  src/pages/profileEdit/ProfileEdit.jsx
  src/redux/modules/AuctionListSlice.js
  src/redux/modules/MyPageSlice.js
Labels: MVP P2

#96 [Feat] 옥션 좋아요, 마이페이지 페이지네이션 , 옥션 글쓰기 css, 컴포넌트 이동 수정
  src/App.js
  src/components/auctionBody/AuctionColumn.jsx
  src/components/auctionBody/AuctionHeart.jsx
  src/components/auctionBody/AuctionRow.jsx
  src/components/auctionBody/AuctionStateNav.jsx
  src/components/pageElement/MyPageList.jsx
  src/components/swipeImage/Slider.jsx
  src/elements/input/Input.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionList/AuctionList.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/main/Main.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageEdit.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/redux/modules/AuctionSlice.js
  src/redux/modules/MyPageSlice.js
  src/shared/Theme.jsx
  src/shared/images/icon/HeartEmpty.svg
  src/shared/images/icon/HeartFull.svg
  src/shared/images/icon/ImgDelete.svg
  src/shared/images/icon/ImgPlus.svg
  src/shared/images/index.js
Labels: MVP P3

#107 [Feat]Feature/bugfix/ 옥션 글쓰기 제한 기능 추가, 시작가 최고 기능 추가, 이미지 삭제 기능 오류 수정
  src/components/header/Header.jsx
  src/pages/auctionReview/AuctionReview.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageEdit.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
Labels: bug

#111 [Feat]Feature/bugfix/마이페이지 내 옥션 수정, 참여 옥션 수정, 타이머 수정
  src/components/auctionBody/AuctionColumn.jsx
  src/components/auctionBody/AuctionRow.jsx
  src/components/auctionBody/AuctionStateNav.jsx
  src/components/countDownTimer/CountDownTimer.jsx
  src/components/swipeImage/Slider.jsx
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
  src/pages/myPage/MyPageInterestAuction.jsx
  src/pages/myPage/MyPageMyAuction.jsx
  src/pages/myPage/MyPageParticipationAuction.jsx
  src/redux/modules/MyPageSlice.js
Labels: bug

#122 [feat]옥션 디테일. 옥션 마이페이지 카카오 이름 수정,
  src/pages/auctionDetail/AuctionDetail.jsx
  src/pages/auctionWrite/AuctionWrite.jsx
  src/pages/myPage/MyPage.jsx
Labels: bug
